const APIS_LIST = {
  "_management": '/management', // links
  "_management_configprops": '/management/configprops', // handle
  "_management_env": '/management/env', // handle
  "_management_env_{toMatch}": '/management/env/{toMatch}', // handle
  "_management_health": '/management/health', // handle
  "_management_health_**": '/management/health/**', // handle
  "_management_info": '/management/info', // handle
  "_management_jhimetrics": '/management/jhimetrics', // handle
  "_management_logfile": '/management/logfile', // handle
  "_management_loggers": '/management/loggers', // handle
  "_management_loggers_{name}": '/management/loggers/{name}', // handle
  "_management_prometheus": '/management/prometheus', // handle
  "_management_threaddump": '/management/threaddump', // handle
  "_account_relative_auth_menu_tree_platform": '/account-relative/auth-menu-tree-platform', // 用户系统菜单权限树
  "_account_relative_update_pwd": '/account-relative/update-pwd', // 首次登录更改密码
  "_api_coupon_add": '/api/coupon/add', // 新增优惠券
  "_api_coupon_categoryList": '/api/coupon/categoryList', // 分类列表
  "_api_coupon_continue": '/api/coupon/continue', // 继续发放优惠券
  "_api_coupon_couponProductPage": '/api/coupon/couponProductPage', // 优惠券商品分页列表
  "_api_coupon_delete": '/api/coupon/delete', // 批量删除优惠券
  "_api_coupon_detail": '/api/coupon/detail', // 优惠券明细
  "_api_coupon_effectiveData": '/api/coupon/effectiveData', // 优惠券效果数据
  "_api_coupon_exchange": '/api/coupon/exchange', // 兑换优惠券
  "_api_coupon_exchangePage": '/api/coupon/exchangePage', // 优惠券兑换分页列表
  "_api_coupon_issuePage": '/api/coupon/issuePage', // 领券中心分页列表
  "_api_coupon_merchantPage": '/api/coupon/merchantPage', // 商户分页列表
  "_api_coupon_myCouponPage": '/api/coupon/myCouponPage', // 我的优惠券分页列表
  "_api_coupon_page": '/api/coupon/page', // 优惠券管理分页列表
  "_api_coupon_pause": '/api/coupon/pause', // 暂停优惠券
  "_api_coupon_productPage": '/api/coupon/productPage', // 商品分页列表
  "_api_coupon_receive": '/api/coupon/receive', // 领取优惠券
  "_api_coupon_receivePage": '/api/coupon/receivePage', // 优惠券领取分页列表
  "_api_coupon_select": '/api/coupon/select', // 选择优惠券
  "_api_coupon_stop": '/api/coupon/stop', // 停止优惠券
  "_api_coupon_update": '/api/coupon/update', // 修改优惠券
  "_api_coupon_useTagList": '/api/coupon/useTagList', // 用户标签列表
  "_auth_login": '/auth/login', // 用户密码登录
  "_auth_logout": '/auth/logout', // 登出
  "_auth_teach_login": '/auth/teach/login', // 教师端授权登录
  "_auth_wx_login": '/auth/wx/login', // 微信授权登录
  "_captcha_check": '/captcha/check', // check
  "_captcha_get": '/captcha/get', // get
  "_common_download": '/common/download', // 通用下载请求
  "_common_file": '/common/file', // 文件上传(自动获取文件名)
  "_common_file_download": '/common/file-download', // 下载文件
  "_common_location": '/common/location', // 获取省市区
  "_dict_createDict": '/dict/createDict', // 新增字典信息
  "_dict_getDictByGroupNos": '/dict/getDictByGroupNos', // 根据组别查询字典信息（逗号分隔字符串）
  "_dict_getDictById": '/dict/getDictById', // 根据id查询字典信息
  "_dict_nation": '/dict/nation', // 民族字典表
  "_dict_removeById": '/dict/removeById', // 根据id删除字典信息
  "_dict_updateDict": '/dict/updateDict', // 修改字典信息
  "_drop_down_campus_box": '/drop-down/campus-box', // 校区下拉框
  "_drop_down_campus_list": '/drop-down/campus-list', // 校区下拉框
  "_drop_down_class_info_list": '/drop-down/class-info-list', // 班级下拉
  "_drop_down_course_class_list": '/drop-down/course-class-list', // 校区课程-班级列表下拉
  "_drop_down_course_list": '/drop-down/course-list', // 课程下拉
  "_drop_down_eva_item_box": '/drop-down/eva-item-box', // 测评项目下拉
  "_drop_down_find_classroom": '/drop-down/find-classroom', // 课表管理-查询教室
  "_drop_down_in_school_student": '/drop-down/in-school-student', // 在学学员下拉
  "_drop_down_item_list": '/drop-down/item-list', // 项目下拉框
  "_drop_down_list": '/drop-down/list', // 查询结算配置列表下拉
  "_drop_down_organization_info": '/drop-down/organization-info', // 机构下拉
  "_drop_down_package_list": '/drop-down/package-list', // 套餐下拉
  "_drop_down_product_box": '/drop-down/product-box', // 商品下拉
  "_drop_down_prospective_customer_list": '/drop-down/prospective-customer-list', // 意向学员下拉
  "_drop_down_select_all": '/drop-down/select-all', // 查询全部商品分组
  "_drop_down_select_tree": '/drop-down/select-tree', // 查出全部商品类目树
  "_drop_down_staff_list": '/drop-down/staff-list', // 上课老师/班主任下拉
  "_drop_down_tag_list": '/drop-down/tag-list', // 标签下拉
  "_drop_down_teaching_evaluate_template_list": '/drop-down/teaching-evaluate-template-list', // 教学评价模板下拉
  "_drop_down_wx_user_list": '/drop-down/wx-user-list', // 推介人
  "_error": '/error', // error
  "_exception_ex1": '/exception/ex1', // 抛出系统异常
  "_exception_ex2": '/exception/ex2', // 抛出业务异常
  "_exception_ex3": '/exception/ex3', // 抛出运行时异常
  "_operation_account_add": '/operation/account/add', // 添加
  "_operation_account_all_role": '/operation/account/all-role', // 添加页获取所有角色
  "_operation_account_delete": '/operation/account/delete', // 删除
  "_operation_account_edit": '/operation/account/edit', // 编辑
  "_operation_account_page": '/operation/account/page', // 分页查询
  "_operation_account_reset_pwd": '/operation/account/reset-pwd', // 重置密码
  "_operation_account_update_status": '/operation/account/update-status', // 启用/停用
  "_operation_banner_config_add": '/operation/banner-config/add', // 添加
  "_operation_banner_config_del": '/operation/banner-config/del', // 删除
  "_operation_banner_config_page": '/operation/banner-config/page', // 查询海报列表列表
  "_operation_banner_config_update": '/operation/banner-config/update', // 修改
  "_operation_commission_audit_audit_reject_by_id": '/operation/commission-audit/audit-reject-by-id', // 审核不通过
  "_operation_commission_audit_audit_success_by_id": '/operation/commission-audit/audit-success-by-id', // 审核通过
  "_operation_commission_audit_export": '/operation/commission-audit/export', // 导出
  "_operation_commission_audit_find_commission_audit": '/operation/commission-audit/find-commission-audit', // 提现列表
  "_operation_commission_audit_payment_retry_by_id": '/operation/commission-audit/payment-retry-by-id', // 再次转账
  "_operation_coursepackageaudit_audit": '/operation/coursepackageaudit/audit', // 审核
  "_operation_coursepackageaudit_page": '/operation/coursepackageaudit/page', // 查询套餐审核列表
  "_operation_info_classify_add": '/operation/info-classify/add', // 添加资讯分类
  "_operation_info_classify_delete": '/operation/info-classify/delete', // 删除资讯分类
  "_operation_info_classify_select_page": '/operation/info-classify/select-page', // 查询全部资讯分类-带分页
  "_operation_info_classify_update": '/operation/info-classify/update', // 修改资讯分类
  "_operation_info_management_add": '/operation/info-management/add', // 添加资讯
  "_operation_info_management_delete": '/operation/info-management/delete', // 删除资讯
  "_operation_info_management_select_class": '/operation/info-management/select-class', // 查询全部资讯分类
  "_operation_info_management_select_page": '/operation/info-management/select-page', // 查询全部资讯-带分页
  "_operation_info_management_update": '/operation/info-management/update', // 修改资讯状态
  "_operation_menu_add": '/operation/menu/add', // 添加菜单
  "_operation_menu_all_list": '/operation/menu/all-list', // 获取所有菜单
  "_operation_menu_delete": '/operation/menu/delete', // 删除
  "_operation_menu_tree": '/operation/menu/tree', // 获取菜单树
  "_operation_menu_update": '/operation/menu/update', // 修改菜单
  "_operation_organization_add": '/operation/organization/add', // 添加机构
  "_operation_organization_adjust_expire_date": '/operation/organization/adjust-expire-date', // 调整到期时间
  "_operation_organization_page": '/operation/organization/page', // 分页
  "_operation_organization_recommend_status": '/operation/organization/recommend-status', // 修改推荐机构状态
  "_operation_organization_reset_pwd": '/operation/organization/reset-pwd', // 重置密码
  "_operation_organization_update": '/operation/organization/update', // 修改机构
  "_operation_organization_update_audit_status": '/operation/organization/update-audit-status', // 开启/关闭审核
  "_operation_organization_update_status": '/operation/organization/update-status', // 启用/停用
  "_operation_pay_payNotify": '/operation/pay/payNotify', // 支付回调接口
  "_operation_pay_refundsNotify": '/operation/pay/refundsNotify', // 退款回调接口
  "_operation_product_category_add_category": '/operation/product-category/add-category', // 添加商品类目
  "_operation_product_category_delete_category_by_id": '/operation/product-category/delete-category-by-id', // 根据id删除类目及其下级目录
  "_operation_product_category_select_is_product_by_id": '/operation/product-category/select-is-product-by-id', // 根据id查询该类目下是否有商品
  "_operation_product_category_select_ne_id": '/operation/product-category/select-ne-id', // 查出全部商品类目树-不带自己
  "_operation_product_category_select_tree": '/operation/product-category/select-tree', // 查出全部商品类目树
  "_operation_product_category_select_tree_by_id": '/operation/product-category/select-tree-by-id', // 根据id查出指定目录包括其子目录
  "_operation_product_category_select_tree_by_pid": '/operation/product-category/select-tree-by-pid', // 根据父级id查出父级名字
  "_operation_product_category_update_category_by_id": '/operation/product-category/update-category-by-id', // 根据id修改类目
  "_operation_protocol_management_add": '/operation/protocol-management/add', // 添加协议
  "_operation_protocol_management_delete": '/operation/protocol-management/delete', // 删除协议
  "_operation_protocol_management_select_all": '/operation/protocol-management/select-all', // 查询协议内容
  "_operation_protocol_management_select_page": '/operation/protocol-management/select-page', // 查询全部协议-带分页
  "_operation_protocol_management_update": '/operation/protocol-management/update', // 编辑协议
  "_operation_protocol_management_update_status": '/operation/protocol-management/update-status', // 修改协议状态
  "_operation_recommend_course_add": '/operation/recommend-course/add', // 添加推荐课程
  "_operation_recommend_course_campus_list": '/operation/recommend-course/campus-list', // 校区下拉框
  "_operation_recommend_course_course_list": '/operation/recommend-course/course-list', // 课程下拉
  "_operation_recommend_course_course_page": '/operation/recommend-course/course-page', // 分页查询推荐课程列表
  "_operation_recommend_course_del": '/operation/recommend-course/del', // 删除推荐课程状态
  "_operation_recommend_course_info": '/operation/recommend-course/info', // 查询商品详情
  "_operation_recommend_course_organization_info": '/operation/recommend-course/organization-info', // 机构下拉
  "_operation_recommend_course_product_category": '/operation/recommend-course/product-category', // 查出全部商品类目树
  "_operation_recommend_course_product_page": '/operation/recommend-course/product-page', // 分页查询商品列表
  "_operation_recommend_course_select_all": '/operation/recommend-course/select-all', // 查询全部商品分组
  "_operation_recommend_course_states": '/operation/recommend-course/states', // 修改推荐课程状态
  "_operation_role_add": '/operation/role/add', // 添加
  "_operation_role_auth": '/operation/role/auth', // 编辑页角色已有权限
  "_operation_role_delete": '/operation/role/delete', // 删除
  "_operation_role_page": '/operation/role/page', // 分页
  "_operation_role_tree": '/operation/role/tree', // 添加页面菜单树
  "_operation_role_update": '/operation/role/update', // 编辑
  "_operation_settlement_price_config_audit": '/operation/settlement-price-config/audit', // 审核分账机制
  "_operation_settlement_price_config_page": '/operation/settlement-price-config/page', // 分页查询审核信息
  "_operation_settlement_price_config_settlement_list": '/operation/settlement-price-config/settlement/list', // 分账周期下拉
  "_operation_sys_account_info": '/operation/sys-account/info', // 查询账号信息
  "_operation_sys_account_update": '/operation/sys-account/update', // 修改账号信息
  "_operation_sys_account_update_pwd": '/operation/sys-account/update-pwd', // 修改密码
  "_operation_sys_config_list": '/operation/sys-config/list', // 查询系统配置列表
  "_operation_sys_config_update": '/operation/sys-config/update', // 修改系统配置
  "_operation_sys_user_init": '/operation/sys-user/init', // 初始化当前会员钱包
  "_operation_sys_user_page": '/operation/sys-user/page', // 查询会员列表
  "_organization_activity_order_export": '/organization/activity-order/export', // 导出
  "_organization_activity_order_page": '/organization/activity-order/page', // 分页列表
  "_organization_activity_order_refund": '/organization/activity-order/refund', // 退款
  "_organization_add_customer_add": '/organization/add_customer/add', // 添加客户
  "_organization_banner_add": '/organization/banner/add', // 添加
  "_organization_banner_page": '/organization/banner/page', // 查询列表
  "_organization_banner_update": '/organization/banner/update', // 修改
  "_organization_campus_add": '/organization/campus/add', // 添加校区
  "_organization_campus_del": '/organization/campus/del', // 删除校区
  "_organization_campus_page": '/organization/campus/page', // 查询校区列表
  "_organization_campus_update": '/organization/campus/update', // 修改校区
  "_organization_campus_update_status": '/organization/campus/update-status', // 停用启用
  "_organization_class_course_edu_add": '/organization/class-course-edu/add', // 添加排课/课程表
  "_organization_class_course_edu_add_stu": '/organization/class-course-edu/add-stu', // 课表添加学员1.4.0
  "_organization_class_course_edu_arranged_stu_list": '/organization/class-course-edu/arranged-stu-list', // 已排课学员列表1.4.0
  "_organization_class_course_edu_class_course_list": '/organization/class-course-edu/class-course-list', // 预约课下拉
  "_organization_class_course_edu_del": '/organization/class-course-edu/del', // 删除排课/课程表
  "_organization_class_course_edu_determine_the": '/organization/class-course-edu/determine-the', // 添加排课，数据校验
  "_organization_class_course_edu_find": '/organization/class-course-edu/find', // 课表管理-查询
  "_organization_class_course_edu_remove_stu": '/organization/class-course-edu/remove-stu', // 课表删除学员1.4.0
  "_organization_class_course_edu_update": '/organization/class-course-edu/update', // 更换教师
  "_organization_class_course_edu_wait_arrange_stu_list": '/organization/class-course-edu/wait-arrange-stu-list', // 待排课学员列表1.4.0
  "_organization_class_course_find_find": '/organization/class-course-find/find', // 课表管理-查询
  "_organization_class_info_add": '/organization/class-info/add', // 添加班级
  "_organization_class_info_del": '/organization/class-info/del', // 删除班级
  "_organization_class_info_detail": '/organization/class-info/detail', // 学员详情
  "_organization_class_info_over": '/organization/class-info/over', // 结课
  "_organization_class_info_page": '/organization/class-info/page', // 查询班级列表
  "_organization_class_info_update": '/organization/class-info/update', // 修改班级
  "_organization_class_record_detail_page": '/organization/class-record/detail-page', // 详情分页
  "_organization_class_record_page": '/organization/class-record/page', // 上课记录分页（统计未结课的非虚拟班级下的未到期未结业的学员）
  "_organization_class_student_details": '/organization/class-student/details', // 查询学员详情
  "_organization_class_student_page": '/organization/class-student/page', // 查询班级学生列表(未结业，未到期学员)
  "_organization_classroom_add": '/organization/classroom/add', // 添加教室
  "_organization_classroom_del": '/organization/classroom/del', // 删除教室
  "_organization_classroom_page": '/organization/classroom/page', // 查询教室列表
  "_organization_classroom_update": '/organization/classroom/update', // 修改教室
  "_organization_course_classify_add": '/organization/course-classify/add', // 添加课程分类
  "_organization_course_classify_del": '/organization/course-classify/del', // 删除课程分类
  "_organization_course_classify_is_course": '/organization/course-classify/is-course', // 根据id查询分类下是否有启用课程
  "_organization_course_classify_page": '/organization/course-classify/page', // 课程分类分页查询
  "_organization_course_classify_update": '/organization/course-classify/update', // 修改课程分类
  "_organization_course_config_add": '/organization/course-config/add', // 添加课程
  "_organization_course_config_course_classify_list": '/organization/course-config/course-classify-list', // 查询组织下课程分类列表
  "_organization_course_config_del": '/organization/course-config/del', // 删除课程
  "_organization_course_config_is_link_product": '/organization/course-config/is-link-product', // 根据id查询分类下是否有启用课程
  "_organization_course_config_is_link_student": '/organization/course-config/is-link-student', // 根据id查询是否有学生未上完课时
  "_organization_course_config_is_status": '/organization/course-config/is-status', // 修改课程启用禁用
  "_organization_course_config_page": '/organization/course-config/page', // 查询课程列表
  "_organization_course_config_update": '/organization/course-config/update', // 修改课程
  "_organization_courseConfig_add": '/organization/courseConfig/add', // 添加课程
  "_organization_courseConfig_del": '/organization/courseConfig/del', // 删除课程
  "_organization_courseConfig_page": '/organization/courseConfig/page', // 查询课程列表
  "_organization_courseConfig_update": '/organization/courseConfig/update', // 修改课程
  "_organization_courseorder_page": '/organization/courseorder/page', // 查询课程订单列表
  "_organization_courseorder_updateOrderStatus": '/organization/courseorder/updateOrderStatus', // 更新订单信息
  "_organization_courseorderrefund_findRefundTrade": '/organization/courseorderrefund/findRefundTrade', // 查询退课记录列表:1.3.0
  "_organization_courseorderrefund_getTeacher": '/organization/courseorderrefund/getTeacher', // 操作教师下拉
  "_organization_courseorderrefund_refundTradeById": '/organization/courseorderrefund/refundTradeById', // 查询退课记录详情:1.3.0
  "_organization_coursepackageconfig_add": '/organization/coursepackageconfig/add', // 添加套餐
  "_organization_coursepackageconfig_cancel": '/organization/coursepackageconfig/cancel', // 撤销审核
  "_organization_coursepackageconfig_del": '/organization/coursepackageconfig/del', // 删除套餐
  "_organization_coursepackageconfig_page": '/organization/coursepackageconfig/page', // 查询套餐列表
  "_organization_coursepackageconfig_submit": '/organization/coursepackageconfig/submit', // 提交
  "_organization_coursepackageconfig_update": '/organization/coursepackageconfig/update', // 修改套餐
  "_organization_evaluation_report_can_choice": '/organization/evaluation-report/can-choice', // 获取报告复选框可选项
  "_organization_evaluation_report_create_report": '/organization/evaluation-report/create-report', // 创建体质评估报告
  "_organization_evaluation_report_delete": '/organization/evaluation-report/delete', // 删除
  "_organization_evaluation_report_detail": '/organization/evaluation-report/detail', // 查看
  "_organization_evaluation_report_detail_list": '/organization/evaluation-report/detail-list', // 根据项目查询评估标准数据
  "_organization_evaluation_report_edit": '/organization/evaluation-report/edit', // 编辑
  "_organization_evaluation_report_page": '/organization/evaluation-report/page', // 分页
  "_organization_evaluation_report_stu_details": '/organization/evaluation-report/stu-details', // 查询学员详情
  "_organization_evaluation_report_student": '/organization/evaluation-report/student', // 获取学员下拉列表
  "_organization_evaluation_report_student_intentional_formal": '/organization/evaluation-report/student-intentional-formal', // 新增意向或正式学员
  "_organization_evaluation_report_template_content": '/organization/evaluation-report/template-content', // 模板内容查询
  "_organization_evaluation_standard_add": '/organization/evaluation-standard/add', // 添加
  "_organization_evaluation_standard_delete": '/organization/evaluation-standard/delete', // 外面的删除(这边参数的id要传外面列表的id)
  "_organization_evaluation_standard_detail_delete": '/organization/evaluation-standard/detail-delete', // 详情里的删除
  "_organization_evaluation_standard_detail_list": '/organization/evaluation-standard/detail-list', // 详情列表
  "_organization_evaluation_standard_page": '/organization/evaluation-standard/page', // 外面的分页
  "_organization_evaluation_standard_update": '/organization/evaluation-standard/update', // 修改
  "_organization_health_report_template_add": '/organization/health-report-template/add', // 添加分类
  "_organization_health_report_template_add_item": '/organization/health-report-template/add-item', // 添加健康报告项目明细
  "_organization_health_report_template_del": '/organization/health-report-template/del', // 删除分类
  "_organization_health_report_template_del_item": '/organization/health-report-template/del-item', // 删除健康报告项目明细
  "_organization_health_report_template_item_page": '/organization/health-report-template/item-page', // 查询健康报告项目列表分页
  "_organization_health_report_template_lv_one_list": '/organization/health-report-template/lv-one-list', // 上级类别下拉框
  "_organization_health_report_template_type_tree": '/organization/health-report-template/type-tree', // 体质报告模板左侧树数据查询
  "_organization_health_report_template_update": '/organization/health-report-template/update', // 修改分类
  "_organization_health_report_template_update_item": '/organization/health-report-template/update-item', // 修改健康报告项目明细
  "_organization_holidayconfig_add": '/organization/holidayconfig/add', // 添加假期表
  "_organization_holidayconfig_del": '/organization/holidayconfig/del', // 删除假期表
  "_organization_holidayconfig_page": '/organization/holidayconfig/page', // 查询假期表列表
  "_organization_holidayconfig_update": '/organization/holidayconfig/update', // 修改假期表
  "_organization_info_classify_add": '/organization/info-classify/add', // 添加资讯分类
  "_organization_info_classify_delete": '/organization/info-classify/delete', // 删除资讯分类
  "_organization_info_classify_select_page": '/organization/info-classify/select-page', // 查询全部资讯分类-带分页
  "_organization_info_classify_update": '/organization/info-classify/update', // 修改资讯分类
  "_organization_info_management_add": '/organization/info-management/add', // 添加资讯
  "_organization_info_management_delete": '/organization/info-management/delete', // 删除资讯
  "_organization_info_management_select_class": '/organization/info-management/select-class', // 查询全部资讯分类
  "_organization_info_management_select_page": '/organization/info-management/select-page', // 查询全部资讯-带分页
  "_organization_info_management_update": '/organization/info-management/update', // 修改资讯状态
  "_organization_itemconfig_add": '/organization/itemconfig/add', // 添加项目配置
  "_organization_itemconfig_del": '/organization/itemconfig/del', // 删除项目配置
  "_organization_itemconfig_page": '/organization/itemconfig/page', // 查询项目配置列表
  "_organization_itemconfig_update": '/organization/itemconfig/update', // 修改项目配置
  "_organization_market_product_add": '/organization/market-product/add', // 添加商品管理
  "_organization_market_product_del": '/organization/market-product/del', // 删除商品管理
  "_organization_market_product_details": '/organization/market-product/details', // 商品详情
  "_organization_market_product_find_list": '/organization/market-product/find-list', // 查出机构商品分类列表
  "_organization_market_product_info": '/organization/market-product/info', // 查询商品详情
  "_organization_market_product_page": '/organization/market-product/page', // 查询商品管理列表
  "_organization_market_product_select_page": '/organization/market-product/select-page', // 查询可报名商品
  "_organization_market_product_total_stock": '/organization/market-product/total-stock', // 修改库存量
  "_organization_market_product_update": '/organization/market-product/update', // 修改商品管理
  "_organization_market_product_update_is_hot": '/organization/market-product/update-is-hot', // 修改热门商品状态
  "_organization_market_product_update_is_sell": '/organization/market-product/update-is-sell', // 修改商品上下架状态
  "_organization_market_order_cancel": '/organization/market/order/cancel', // 订单取消
  "_organization_market_order_compute_coupon": '/organization/market/order/compute-coupon', // 选择优惠券计算优惠金额
  "_organization_market_order_create_order": '/organization/market/order/create-order', // 报名-生成订单(购课)
  "_organization_market_order_del": '/organization/market/order/del', // 订单删除
  "_organization_market_order_details": '/organization/market/order/details', // 订单详情
  "_organization_market_order_page": '/organization/market/order/page', // 查询订单列表
  "_organization_market_order_pay_by_offline": '/organization/market/order/pay-by-offline', // 订单线下付款
  "_organization_market_order_pay_by_qrcode": '/organization/market/order/pay-by-qrcode', // 订单支付(生成支付二维码)
  "_organization_market_order_query_pay_status": '/organization/market/order/query-pay-status', // 支付结果查询
  "_organization_market_order_refund": '/organization/market/order/refund', // 订单退款
  "_organization_message_notify_no_read": '/organization/message-notify/no_read', // 未读消息条数
  "_organization_message_notify_page": '/organization/message-notify/page', // 查询消息通知列表
  "_organization_message_notify_readed": '/organization/message-notify/readed', // 批量标记已读
  "_organization_notification_list": '/organization/notification/list', // 通知列表
  "_organization_notification_update": '/organization/notification/update', // 修改通知
  "_organization_operating_statement_educational_list": '/organization/operating-statement/educational-list', // 教务分析统计
  "_organization_operating_statement_registration_list": '/organization/operating-statement/registration-list', // 报名情况统计
  "_organization_operating_statement_should_page": '/organization/operating-statement/should-page', // 人次明细
  "_organization_operating_statement_student_page": '/organization/operating-statement/student-page', // 累计学员数明细
  "_organization_order_commission_export": '/organization/order-commission/export', // 导出
  "_organization_order_commission_page": '/organization/order-commission/page', // 查询列表
  "_organization_organization_info_detail": '/organization/organization-info/detail', // 机构信息详情
  "_organization_organization_info_update": '/organization/organization-info/update', // 修改机构信息
  "_organization_organizationstaff_add": '/organization/organizationstaff/add', // 添加员工信息
  "_organization_organizationstaff_all_role": '/organization/organizationstaff/all-role', // 添加页获取所有角色
  "_organization_organizationstaff_del": '/organization/organizationstaff/del', // 删除职工信息
  "_organization_organizationstaff_queryStaff": '/organization/organizationstaff/queryStaff', // 查询职工信息
  "_organization_organizationstaff_update": '/organization/organizationstaff/update', // 修改职工信息
  "_organization_organizationstaff_update_pwd": '/organization/organizationstaff/update-pwd', // 重置密码
  "_organization_organizationstaff_updateStatus": '/organization/organizationstaff/updateStatus', // 修改状态
  "_organization_organizationstaffwage_delete_wage": '/organization/organizationstaffwage/delete-wage', // 删除工资信息
  "_organization_organizationstaffwage_find_staff_all": '/organization/organizationstaffwage/find-staff-all', // 查询所有员工信息
  "_organization_organizationstaffwage_insert_wage": '/organization/organizationstaffwage/insert-wage', // 添加工资信息
  "_organization_organizationstaffwage_select_all_by_id": '/organization/organizationstaffwage/select-all-by-id', // 根据员工id查询工资
  "_organization_organizationstaffwage_select_page": '/organization/organizationstaffwage/select-page', // 查询全部工资-带分页
  "_organization_organizationstaffwage_update_wage": '/organization/organizationstaffwage/update-wage', // 修改工资信息
  "_organization_personal_center_detail": '/organization/personal-center/detail', // 详情
  "_organization_personal_center_upd_pwd": '/organization/personal-center/upd-pwd', // 修改密码
  "_organization_personal_center_update": '/organization/personal-center/update', // 修改资料
  "_organization_product_group_add_group": '/organization/product-group/add-group', // 添加商品分组
  "_organization_product_group_delete_by_id": '/organization/product-group/delete-by-id', // 根据id删除分组
  "_organization_product_group_select_all": '/organization/product-group/select-all', // 查询全部商品分组
  "_organization_product_group_select_is_product_by_id": '/organization/product-group/select-is-product-by-id', // 根据id查出分组下是否有商品
  "_organization_product_group_select_page": '/organization/product-group/select-page', // 查询全部商品分组-带分页
  "_organization_product_group_update_by_id": '/organization/product-group/update-by-id', // 根据id修改分组
  "_organization_product_type_add": '/organization/product-type/add', // 添加商品类型
  "_organization_product_type_del": '/organization/product-type/del', // 删除商品类型
  "_organization_product_type_is_product": '/organization/product-type/is-product', // 根据id查询类型下是否有商品
  "_organization_product_type_page": '/organization/product-type/page', // 商品类型分页查询
  "_organization_product_type_update": '/organization/product-type/update', // 修改商品类型
  "_organization_projects_management_add_projects": '/organization/projects-management/add-projects', // 添加项目
  "_organization_projects_management_delete_projects": '/organization/projects-management/delete-projects', // 删除项目
  "_organization_projects_management_search_projects": '/organization/projects-management/search-projects', // 查询项目
  "_organization_projects_management_update_projects": '/organization/projects-management/update-projects', // 修改项目
  "_organization_prospectivecustomer_addFollow": '/organization/prospectivecustomer/addFollow', // 添加跟进记录
  "_organization_prospectivecustomer_del": '/organization/prospectivecustomer/del', // 删除客户
  "_organization_prospectivecustomer_finishFollow": '/organization/prospectivecustomer/finishFollow', // 结束跟进
  "_organization_prospectivecustomer_followRecordPage": '/organization/prospectivecustomer/followRecordPage', // 分页查询跟进记录列表
  "_organization_prospectivecustomer_getDetail": '/organization/prospectivecustomer/getDetail', // 获取客户详情
  "_organization_prospectivecustomer_page": '/organization/prospectivecustomer/page', // 查询客户列表
  "_organization_prospectivecustomer_reserve": '/organization/prospectivecustomer/reserve', // 约课
  "_organization_prospectivecustomer_reserveList": '/organization/prospectivecustomer/reserveList', // 约课试听时间下拉
  "_organization_prospectivecustomer_reservePage": '/organization/prospectivecustomer/reservePage', // 分页查询预约记录列表
  "_organization_prospectivecustomer_update": '/organization/prospectivecustomer/update', // 修改客户
  "_organization_report_financial_statistics_details": '/organization/report-financial-statistics/details', // 财务统计明细
  "_organization_report_financial_statistics_list": '/organization/report-financial-statistics/list', // 财务统计
  "_organization_reserve_record_reservePage": '/organization/reserve-record/reservePage', // 预约记录列表
  "_organization_role_add": '/organization/role/add', // 添加
  "_organization_role_auth": '/organization/role/auth', // 编辑页角色已有权限
  "_organization_role_delete": '/organization/role/delete', // 删除
  "_organization_role_page": '/organization/role/page', // 分页
  "_organization_role_tree": '/organization/role/tree', // 获取菜单树
  "_organization_role_update": '/organization/role/update', // 编辑
  "_organization_settlement_config_add": '/organization/settlement-config/add', // 添加结算配置
  "_organization_settlement_config_del": '/organization/settlement-config/del', // 删除结算配置
  "_organization_settlement_config_del_detail": '/organization/settlement-config/del-detail', // 删除结算配置详情数据
  "_organization_settlement_config_page": '/organization/settlement-config/page', // 查询结算配置列表
  "_organization_settlement_config_update": '/organization/settlement-config/update', // 修改结算配置
  "_organization_settlement_config_update_status": '/organization/settlement-config/update-status', // 修改状态
  "_organization_settlement_price_config_alter": '/organization/settlement-price-config/alter', // 变更配置信息
  "_organization_settlement_price_config_del": '/organization/settlement-price-config/del', // 删除配置信息
  "_organization_settlement_price_config_list": '/organization/settlement-price-config/list', // 分账配置列表
  "_organization_settlement_price_config_retract": '/organization/settlement-price-config/retract', // 撤回配置信息
  "_organization_settlement_price_config_save_update": '/organization/settlement-price-config/save-update', // 添加修改结算配置
  "_organization_settlement_price_config_settlement_config": '/organization/settlement-price-config/settlement-config', // 查询商品价格所处的分账周期
  "_organization_settlement_price_config_settlement_config_detail": '/organization/settlement-price-config/settlement-config/detail', // 查询分账周期详细信息
  "_organization_settlement_price_config_settlement_list": '/organization/settlement-price-config/settlement/list', // 分账周期下拉
  "_organization_student_attendance_add_stu": '/organization/student-attendance/add-stu', // 课表添加学员1.4.0
  "_organization_student_attendance_course_info": '/organization/student-attendance/course-info', // 左侧日历课表信息
  "_organization_student_attendance_info": '/organization/student-attendance/info', // 右侧学员考勤信息（只显示该课程未结业且未到期的学员）
  "_organization_student_attendance_remove_stu": '/organization/student-attendance/remove-stu', // 课表删除学员1.4.0
  "_organization_student_attendance_to_attendance": '/organization/student-attendance/to-attendance', // 去考勤
  "_organization_student_attendance_wait_arrange_stu_list": '/organization/student-attendance/wait-arrange-stu-list', // 待排课学员列表1.4.0
  "_organization_student_detail_classRecord": '/organization/student-detail/classRecord', // 上课记录列表
  "_organization_student_detail_details": '/organization/student-detail/details', // 查询学员详情
  "_organization_student_detail_followUpRecord": '/organization/student-detail/followUpRecord', // 分页查询跟进记录列表
  "_organization_student_detail_order_details": '/organization/student-detail/order-details', // 订单详情:V1.3.0
  "_organization_student_detail_order_page": '/organization/student-detail/order-page', // 查询订单列表:V1.3.0
  "_organization_student_detail_pay_page": '/organization/student-detail/pay-page', // 缴费记录:V1.3.0
  "_organization_student_detail_studentResult": '/organization/student-detail/studentResult', // 查询学员成绩列表
  "_organization_student_detail_teachingEvaluation": '/organization/student-detail/teachingEvaluation', // 分页查询教学评价列表
  "_organization_student_history_course_list": '/organization/student-history/course-list', // 查询历史在学课程列表:1.4.0版本
  "_organization_student_history_details": '/organization/student-history/details', // 查询历史学员详情
  "_organization_student_history_page": '/organization/student-history/page', // 查询历史学员列表
  "_organization_studentclassfeedback_page": '/organization/studentclassfeedback/page', // 查询列表
  "_organization_studentcourse_course_list": '/organization/studentcourse/course-list', // 查询在学课程列表:1.3.0版本
  "_organization_studentcourse_graduation": '/organization/studentcourse/graduation', // 结课:1.3.0版本
  "_organization_studentcourse_judgment_status": '/organization/studentcourse/judgment-status', // 待付款调用:1.3.0版本
  "_organization_studentcourse_product_id": '/organization/studentcourse/product-id', // 查询商品ID:1.3.0版本
  "_organization_studentcourse_refundCourse": '/organization/studentcourse/refundCourse', // 退课:1.3.0版本
  "_organization_studentcourse_refundCourseOrderInfo": '/organization/studentcourse/refundCourseOrderInfo', // 退课订单信息:1.3.0版本
  "_organization_studentcourse_renewal": '/organization/studentcourse/renewal', // 续费:1.3.0版本
  "_organization_studentcourse_stay_divide_class": '/organization/studentcourse/stay-divide-class', // 待分班列表v1.4.0
  "_organization_studentcourse_transfer_course": '/organization/studentcourse/transfer-course', // 转课:1.3.0版本
  "_organization_studentcourse_transfer_course_detail": '/organization/studentcourse/transfer-course-detail', // 转课订单详:1.3.0版本
  "_organization_studentcourse_winding_up": '/organization/studentcourse/winding-up', // 结业:1.4.0版本
  "_organization_studentresult_add": '/organization/studentresult/add', // 添加成绩
  "_organization_studentresult_del": '/organization/studentresult/del', // 删除成绩
  "_organization_studentresult_del_item": '/organization/studentresult/del-item', // 删除项目成绩
  "_organization_studentresult_page": '/organization/studentresult/page', // 查询成绩列表
  "_organization_studentresult_update": '/organization/studentresult/update', // 修改成绩
  "_organization_studying_add_student": '/organization/studying/add-student', // 新增学员:1.3.0版本
  "_organization_studying_del_student": '/organization/studying/del-student', // 删除学员
  "_organization_studying_divide_into_classes": '/organization/studying/divide-into-classes', // 分班:1.3.0版本
  "_organization_studying_division_class_list": '/organization/studying/division-class-list', // 获取分班列表:1.3.0版本
  "_organization_studying_excel_import": '/organization/studying/excel/import', // 时长学员导入
  "_organization_studying_getStudentBaseInfo": '/organization/studying/getStudentBaseInfo', // 获取编辑学员信息
  "_organization_studying_stu_evaluation": '/organization/studying/stu-evaluation', // 学员体质测试评估列表
  "_organization_studying_student_page": '/organization/studying/student-page', // 查询在学学员列表:1.3.0版本
  "_organization_studying_template_out": '/organization/studying/template/out', // 学员在学课程导入模板下载
  "_organization_studying_updateStudent": '/organization/studying/updateStudent', // 修改学生信息
  "_organization_suggest_template_classify_add": '/organization/suggest-template-classify/add', // add
  "_organization_suggested_template_add": '/organization/suggested-template/add', // 添加体质测评建议模板
  "_organization_suggested_template_classify_tree": '/organization/suggested-template/classify-tree', // 左侧树
  "_organization_suggested_template_delete": '/organization/suggested-template/delete', // 删除体质测评建议模板
  "_organization_suggested_template_search": '/organization/suggested-template/search', // 查询体质测评建议模板
  "_organization_suggested_template_update": '/organization/suggested-template/update', // 修改体质测评建议模板
  "_organization_tagconfig_add": '/organization/tagconfig/add', // 添加标签配置
  "_organization_tagconfig_del": '/organization/tagconfig/del', // 删除标签配置
  "_organization_tagconfig_page": '/organization/tagconfig/page', // 查询标签配置列表
  "_organization_tagconfig_update": '/organization/tagconfig/update', // 修改标签配置
  "_organization_teaching_evaluate_template_add_item": '/organization/teaching-evaluate-template/add-item', // 添加项目模板
  "_organization_teaching_evaluate_template_add_problem": '/organization/teaching-evaluate-template/add-problem', // 添加问题
  "_organization_teaching_evaluate_template_add_sport": '/organization/teaching-evaluate-template/add-sport', // 添加运动
  "_organization_teaching_evaluate_template_del_item": '/organization/teaching-evaluate-template/del-item', // 删除项目模板
  "_organization_teaching_evaluate_template_del_problem": '/organization/teaching-evaluate-template/del-problem', // 删除问题
  "_organization_teaching_evaluate_template_del_sport": '/organization/teaching-evaluate-template/del-sport', // 删除运动
  "_organization_teaching_evaluate_template_item_page": '/organization/teaching-evaluate-template/item-page', // 查询运动评价列表分页
  "_organization_teaching_evaluate_template_problem_page": '/organization/teaching-evaluate-template/problem-page', // 查询常见问题列表分页
  "_organization_teaching_evaluate_template_sport_tree": '/organization/teaching-evaluate-template/sport-tree', // 教学评价模板左侧树数据查询
  "_organization_teaching_evaluate_template_upd_item": '/organization/teaching-evaluate-template/upd-item', // 更新项目模板
  "_organization_teaching_evaluate_template_upd_problem": '/organization/teaching-evaluate-template/upd-problem', // 更新问题
  "_organization_teaching_evaluate_template_upd_sport": '/organization/teaching-evaluate-template/upd-sport', // 修改运动
  "_organization_teaching_evaluate_evaluate_temp_list": '/organization/teaching-evaluate/evaluate-temp-list', // 评价模板list
  "_organization_teaching_evaluate_page": '/organization/teaching-evaluate/page', // 教学评价列表分页
  "_organization_teaching_evaluate_select_student": '/organization/teaching-evaluate/select-student', // 教学评价学员与课程信息
  "_organization_teaching_evaluate_student_page": '/organization/teaching-evaluate/student-page', // 教学评价学员列表分页
  "_organization_teaching_evaluate_submit_evaluate": '/organization/teaching-evaluate/submit-evaluate', // 提交评价
  "_organization_workbench_find": '/organization/workbench/find', // 工作台
  "_organization_workbench_find_course": '/organization/workbench/find-course', // 课表管理-查询
  "_resource_add": '/resource/add', // 添加
  "_resource_delete": '/resource/delete', // 删除
  "_resource_get_all_list": '/resource/get/all/list', // 查询列表
  "_resource_update": '/resource/update', // 修改
  "_wx_organization_activity_list": '/wx/organization/activity/list', // 查询活动场次列表
  "_wx_organization_activity_update_current_off_status": '/wx/organization/activity/update-current-off-status', // 不是本场次继续核销
  "_wx_organization_activity_update_off_status": '/wx/organization/activity/update-off-status', // 二维码扫码接口
  "_wx_organization_class_course_teacher_add": '/wx/organization/class-course-teacher/add', // 添加排课/课程表
  "_wx_organization_class_course_teacher_add_stu": '/wx/organization/class-course-teacher/add-stu', // 课表添加学员1.4.0
  "_wx_organization_class_course_teacher_arranged_stu_list": '/wx/organization/class-course-teacher/arranged-stu-list', // 已排课学员列表1.4.0
  "_wx_organization_class_course_teacher_del": '/wx/organization/class-course-teacher/del', // 删除排课/课程表
  "_wx_organization_class_course_teacher_determine_the": '/wx/organization/class-course-teacher/determine-the', // 添加排课，数据校验
  "_wx_organization_class_course_teacher_find": '/wx/organization/class-course-teacher/find', // 课表管理-查询
  "_wx_organization_class_course_teacher_find_classroom": '/wx/organization/class-course-teacher/find-classroom', // 课表管理-查询教室
  "_wx_organization_class_course_teacher_remove_stu": '/wx/organization/class-course-teacher/remove-stu', // 课表删除学员1.4.0
  "_wx_organization_class_course_teacher_wait_arrange_stu_list": '/wx/organization/class-course-teacher/wait-arrange-stu-list', // 待排课学员列表1.4.0
  "_wx_organization_class_student_details": '/wx/organization/class-student/details', // 查询学员详情
  "_wx_organization_class_student_stu_list": '/wx/organization/class-student/stu-list', // 查询班级学生列表
  "_wx_organization_courseorder_page": '/wx/organization/courseorder/page', // 订单列表
  "_wx_organization_courseorder_updateOrderStatus": '/wx/organization/courseorder/updateOrderStatus', // 更新订单信息
  "_wx_organization_evaluation_report_evaluation_list": '/wx/organization/evaluation-report/evaluation-list', // 体质评估
  "_wx_organization_home_workbench": '/wx/organization/home/workbench', // 工作台-课表管理
  "_wx_organization_my_banner_list": '/wx/organization/my/banner-list', // 轮播
  "_wx_organization_my_detail": '/wx/organization/my/detail', // 个人信息
  "_wx_organization_my_upd_pwd": '/wx/organization/my/upd-pwd', // 修改密码
  "_wx_organization_my_update": '/wx/organization/my/update', // 修改资料
  "_wx_organization_student_attendance_add_stu": '/wx/organization/student-attendance/add-stu', // 课表添加学员1.4.0
  "_wx_organization_student_attendance_find": '/wx/organization/student-attendance/find', // 课表管理-查询
  "_wx_organization_student_attendance_info": '/wx/organization/student-attendance/info', // 签到详情
  "_wx_organization_student_attendance_remove_stu": '/wx/organization/student-attendance/remove-stu', // 课表删除学员1.4.0
  "_wx_organization_student_attendance_to_attendance": '/wx/organization/student-attendance/to-attendance', // 批量考勤
  "_wx_organization_student_attendance_wait_arrange_stu_list": '/wx/organization/student-attendance/wait-arrange-stu-list', // 待排课学员列表1.4.0
  "_wx_organization_student_health_report_create": '/wx/organization/student-health-report/create', // 创建报告
  "_wx_organization_student_health_report_report_detail": '/wx/organization/student-health-report/report-detail', // 查询报告详情体质总览
  "_wx_organization_student_health_report_report_page": '/wx/organization/student-health-report/report-page', // 查询体质报告列表分页
  "_wx_organization_student_health_report_report_template_list": '/wx/organization/student-health-report/report-template-list', // 获取体质报告模板list
  "_wx_organization_student_health_report_update": '/wx/organization/student-health-report/update', // 编辑报告
  "_wx_organization_studentManage_getStudentBaseInfo": '/wx/organization/studentManage/getStudentBaseInfo', // 获取编辑学员信息
  "_wx_organization_studentManage_page": '/wx/organization/studentManage/page', // 查询学员列表
  "_wx_organization_studentManage_updateStudent": '/wx/organization/studentManage/updateStudent', // 修改学生信息
  "_wx_organization_studentcourse_add_student": '/wx/organization/studentcourse/add-student', // 新增学员:1.4.0版本
  "_wx_organization_studentcourse_create_order": '/wx/organization/studentcourse/create-order', // 报名-生成订单(购课)
  "_wx_organization_studentcourse_divide_into_classes": '/wx/organization/studentcourse/divide-into-classes', // 分班:1.4.0版本
  "_wx_organization_studentcourse_division_class_list": '/wx/organization/studentcourse/division-class-list', // 获取分班列表:1.4.0版本
  "_wx_organization_studentcourse_graduation": '/wx/organization/studentcourse/graduation', // 结课:1.4.0版本
  "_wx_organization_studentcourse_info": '/wx/organization/studentcourse/info', // 查询商品详情
  "_wx_organization_studentcourse_pay_by_offline": '/wx/organization/studentcourse/pay-by-offline', // 订单线下付款
  "_wx_organization_studentcourse_pay_by_qrcode": '/wx/organization/studentcourse/pay-by-qrcode', // 订单支付(生成支付二维码)
  "_wx_organization_studentcourse_query_pay_status": '/wx/organization/studentcourse/query-pay-status', // 支付结果查询
  "_wx_organization_studentcourse_refundCourse": '/wx/organization/studentcourse/refundCourse', // 退课:1.4.0版本
  "_wx_organization_studentcourse_renewal": '/wx/organization/studentcourse/renewal', // 续费:1.4.0版本
  "_wx_organization_studentcourse_select_page": '/wx/organization/studentcourse/select-page', // 查询可报名商品
  "_wx_organization_studentcourse_transfer_course": '/wx/organization/studentcourse/transfer-course', // 转课:1.4.0版本
  "_wx_organization_teaching_evaluate_evaluate_temp_list": '/wx/organization/teaching-evaluate/evaluate-temp-list', // 评价模板list
  "_wx_organization_teaching_evaluate_page": '/wx/organization/teaching-evaluate/page', // 教学评价列表分页
  "_wx_organization_teaching_evaluate_student_page": '/wx/organization/teaching-evaluate/student-page', // 教学评价学员列表
  "_wx_organization_teaching_evaluate_submit_evaluate": '/wx/organization/teaching-evaluate/submit-evaluate', // 提交评价
  "_wx_user_activity_order_details": '/wx/user/activity-order/details', // 活动详情
  "_wx_user_activity_order_paidList": '/wx/user/activity-order/paidList', // 我的活动
  "_wx_user_activity_sign_up_order_addSignUp": '/wx/user/activity-sign-up-order/addSignUp', // 立即报名-创建订单
  "_wx_user_activity_sign_up_order_cancel": '/wx/user/activity-sign-up-order/cancel', // 取消订单
  "_wx_user_activity_sign_up_order_checkExitUnPayOrder": '/wx/user/activity-sign-up-order/checkExitUnPayOrder', // 校验是否报名
  "_wx_user_activity_sign_up_order_generateOffCode": '/wx/user/activity-sign-up-order/generateOffCode', // 获取核销码
  "_wx_user_activity_sign_up_order_getSignUpToken": '/wx/user/activity-sign-up-order/getSignUpToken', // 获取报名token
  "_wx_user_activity_sign_up_order_unPayOrderDetail": '/wx/user/activity-sign-up-order/unPayOrderDetail', // 未支付订单详情
  "_wx_user_activity_find": '/wx/user/activity/find', // 查询活动详情
  "_wx_user_activity_list": '/wx/user/activity/list', // 查询活动场次列表
  "_wx_user_exam_getPic": '/wx/user/exam/getPic', // 获取验证码图片
  "_wx_user_exam_planList": '/wx/user/exam/planList', // 查询计划
  "_wx_user_exam_queryExam": '/wx/user/exam/queryExam', // 查询学生成绩
  "_wx_user_exam_student_login": '/wx/user/exam/student/login', // 学生登录
  "_wx_user_pay_createOrderByJs": '/wx/user/pay/createOrderByJs', // 支付下单
  "_wx_user_pay_queryPayStatus": '/wx/user/pay/queryPayStatus' // 支付结果查询
}
export default APIS_LIST
