const APIS_LIST = {
  "_management": '/management', // links
  "_management_configprops": '/management/configprops', // handle
  "_management_env": '/management/env', // handle
  "_management_env_{toMatch}": '/management/env/{toMatch}', // handle
  "_management_health": '/management/health', // handle
  "_management_health_**": '/management/health/**', // handle
  "_management_info": '/management/info', // handle
  "_management_jhimetrics": '/management/jhimetrics', // handle
  "_management_logfile": '/management/logfile', // handle
  "_management_loggers": '/management/loggers', // handle
  "_management_loggers_{name}": '/management/loggers/{name}', // handle
  "_management_prometheus": '/management/prometheus', // handle
  "_management_threaddump": '/management/threaddump', // handle
  "_account_relative_auth_menu_tree_platform": '/account-relative/auth-menu-tree-platform', // 用户系统菜单权限树
  "_account_relative_update_pwd": '/account-relative/update-pwd', // 首次登录更改密码
  "_campus": '/campus', // 校区下拉
  "_captcha_check": '/captcha/check', // check
  "_captcha_get": '/captcha/get', // get
  "_coach": '/coach', // 教练下拉
  "_common_download": '/common/download', // 通用下载请求
  "_course": '/course', // 课程下拉
  "_error": '/error', // errorHtml
  "_operation_banner_add": '/operation/banner/add', // 添加轮播图
  "_operation_banner_del": '/operation/banner/del', // 删除轮播图
  "_operation_banner_page": '/operation/banner/page', // 查询轮播图列表
  "_operation_banner_upd": '/operation/banner/upd', // 修改轮播图
  "_operation_pay_payNotify": '/operation/pay/payNotify', // 支付回调接口
  "_operation_sys_dict_add": '/operation/sys-dict/add', // 添加字典信息
  "_operation_sys_dict_delete": '/operation/sys-dict/delete', // 删除字典信息
  "_operation_sys_dict_select": '/operation/sys-dict/select', // 条件查询字典信息
  "_operation_sys_dict_select_pid": '/operation/sys-dict/select-pid', // 条件查询字典信息
  "_operation_sys_dict_update": '/operation/sys-dict/update', // 修改字典信息
  "_organization_campus": '/organization-campus', // 运营团队-校区联动下拉
  "_organization_student_list": '/organization/student/list', // 当前登录用户学生集合
  "_organization_student_save": '/organization/student/save', // 保存学生
  "_organization_student_test": '/organization/student/test', // 测试测试
  "_organization_wx_product_get_course": '/organization/wx-product/get-course', // 查询课程
  "_organization_wx_product_get_details": '/organization/wx-product/get-details', // 课程详情
  "_schedule_template": '/schedule-template', // 上课时段列表
  "_wx_campus_apply": '/wx-campus/apply', // 社区申请
  "_wx_coach_apply": '/wx-coach/apply', // 教练申请
  "_wx_organization_class_student_mien": '/wx/organization/class-student/mien', // 班级风采
  "_wx_organization_class_student_page": '/wx/organization/class-student/page', // 班级列表分页
  "_wx_user_center_detail": '/wx/user/center/detail', // 当前登录用户学生集合
  "_wx_user_class_detail": '/wx/user/class/detail', // 获取班级详情
  "_wx_user_class_page": '/wx/user/class/page', // 获取班级分页
  "_wx_user_index_campus_search_list": '/wx/user/index/campus-search-list', // 校区搜索列表
  "_wx_user_index_course_details": '/wx/user/index/course-details', // 商品详情
  "_wx_user_index_initiate_spell_class": '/wx/user/index/initiate-spell-class', // 发起拼班
  "_wx_user_index_mine_spell_class": '/wx/user/index/mine-spell-class', // 我的拼班
  "_wx_user_index_my_spell_class_list": '/wx/user/index/my-spell-class-list', // 我要拼班
  "_wx_user_index_near_spell_class_list": '/wx/user/index/near-spell-class-list', // 附近拼班列表
  "_wx_user_index_product_course_list": '/wx/user/index/product-course-list', // 社区课程列表
  "_wx_user_map_area_campus_list": '/wx/user/map/area-campus-list', // 根据区域code查找校区位置和数量
  "_wx_user_map_campus_list": '/wx/user/map/campus-list', // 校区列表
  "_wx_user_purse_query_pay_status": '/wx/user/purse/query-pay-status', // 支付结果查询
  "_wx_user_purse_recharge": '/wx/user/purse/recharge', // 充值发起
  "_wx_user_purse_trade_list": '/wx/user/purse/trade-list', // 财务流水
  "_wx_user_wx_course_schedule_coach_schedule_stu_info": '/wx/user/wx-course-schedule/coach-schedule-stu-info', // 教练查看-班级详情-查看课表-学员信息
  "_wx_user_wx_course_schedule_view": '/wx/user/wx-course-schedule/view', // 班级详情-查看课表
  "_wx_user_wx_course_schedule_vip_schedule_stu_info": '/wx/user/wx-course-schedule/vip-schedule-stu-info' // 会员查看-班级详情-查看课表-学员信息
}
export default APIS_LIST
